version: 2 
jobs:
  build:
    working_directory: ~/tmp 
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout 
      - run: mvn -B package --file ../GH_Tools/pom.xml
      - run: echo "END OF UNIT TEST";
