/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_guidedhacking_GH_Tools_GHInput */

#ifndef _Included_com_guidedhacking_GH_Tools_GHInput
#define _Included_com_guidedhacking_GH_Tools_GHInput
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_guidedhacking_GH_Tools_GHInput
 * Method:    getKeyDown
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_guidedhacking_GH_1Tools_GHInput_getKeyDown
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_guidedhacking_GH_Tools_GHInput
 * Method:    getKeyPress
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_guidedhacking_GH_1Tools_GHInput_getKeyPress
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_guidedhacking_GH_Tools_GHInput
 * Method:    getKeyPressed
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_guidedhacking_GH_1Tools_GHInput_getKeyPressed
  (JNIEnv *, jclass);

/*
 * Class:     com_guidedhacking_GH_Tools_GHInput
 * Method:    sendKeyPress
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_guidedhacking_GH_1Tools_GHInput_sendKeyPress
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_guidedhacking_GH_Tools_GHInput
 * Method:    sendKeyDown
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_guidedhacking_GH_1Tools_GHInput_sendKeyDown
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_guidedhacking_GH_Tools_GHInput
 * Method:    sendKeyUp
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_guidedhacking_GH_1Tools_GHInput_sendKeyUp
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_guidedhacking_GH_Tools_GHInput
 * Method:    SetCursor
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_guidedhacking_GH_1Tools_GHInput_SetCursor
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_guidedhacking_GH_Tools_GHInput
 * Method:    getCursorPos
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_guidedhacking_GH_1Tools_GHInput_getCursorPos
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
