/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_guidedhacking_GH_Tools_GHMemory */

#ifndef _Included_com_guidedhacking_GH_Tools_GHMemory
#define _Included_com_guidedhacking_GH_Tools_GHMemory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_guidedhacking_GH_Tools_GHMemory
 * Method:    openWindowName
 * Signature: (Ljava/lang/String;Lcom/guidedhacking/GH_Tools/GHArchitecture;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_guidedhacking_GH_1Tools_GHMemory_openWindowName
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_guidedhacking_GH_Tools_GHMemory
 * Method:    openProcess
 * Signature: (Ljava/lang/String;Lcom/guidedhacking/GH_Tools/GHArchitecture;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_guidedhacking_GH_1Tools_GHMemory_openProcess
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_guidedhacking_GH_Tools_GHMemory
 * Method:    isConnected
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_guidedhacking_GH_1Tools_GHMemory_isConnected
  (JNIEnv *, jclass);

/*
 * Class:     com_guidedhacking_GH_Tools_GHMemory
 * Method:    getModuleBaseAddress
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_guidedhacking_GH_1Tools_GHMemory_getModuleBaseAddress__
  (JNIEnv *, jclass);

/*
 * Class:     com_guidedhacking_GH_Tools_GHMemory
 * Method:    getModuleBaseAddress
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_guidedhacking_GH_1Tools_GHMemory_getModuleBaseAddress__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_guidedhacking_GH_Tools_GHMemory
 * Method:    readMemory
 * Signature: (JI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_guidedhacking_GH_1Tools_GHMemory_readMemory
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_guidedhacking_GH_Tools_GHMemory
 * Method:    writeMemory
 * Signature: (J[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_guidedhacking_GH_1Tools_GHMemory_writeMemory
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_guidedhacking_GH_Tools_GHMemory
 * Method:    patchMemory
 * Signature: (J[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_guidedhacking_GH_1Tools_GHMemory_patchMemory
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_guidedhacking_GH_Tools_GHMemory
 * Method:    nopMemory
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_guidedhacking_GH_1Tools_GHMemory_nopMemory
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_guidedhacking_GH_Tools_GHMemory
 * Method:    getObjectAddress
 * Signature: (Lcom/guidedhacking/GH_Tools/GHPointer;)J
 */
JNIEXPORT jlong JNICALL Java_com_guidedhacking_GH_1Tools_GHMemory_getObjectAddress
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_guidedhacking_GH_Tools_GHMemory
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_guidedhacking_GH_1Tools_GHMemory_close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
