/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_guidedhacking_GH_Tools_GHTools */

#ifndef _Included_com_guidedhacking_GH_Tools_GHTools
#define _Included_com_guidedhacking_GH_Tools_GHTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_guidedhacking_GH_Tools_GHTools
 * Method:    getGamePID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_guidedhacking_GH_1Tools_GHTools_getGamePID
  (JNIEnv *, jclass);

/*
 * Class:     com_guidedhacking_GH_Tools_GHTools
 * Method:    isGameVisible
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_guidedhacking_GH_1Tools_GHTools_isGameVisible
  (JNIEnv *, jclass);

/*
 * Class:     com_guidedhacking_GH_Tools_GHTools
 * Method:    getGameHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_guidedhacking_GH_1Tools_GHTools_getGameHeight
  (JNIEnv *, jclass);

/*
 * Class:     com_guidedhacking_GH_Tools_GHTools
 * Method:    getGameWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_guidedhacking_GH_1Tools_GHTools_getGameWidth
  (JNIEnv *, jclass);

/*
 * Class:     com_guidedhacking_GH_Tools_GHTools
 * Method:    getGameXPos
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_guidedhacking_GH_1Tools_GHTools_getGameXPos
  (JNIEnv *, jclass);

/*
 * Class:     com_guidedhacking_GH_Tools_GHTools
 * Method:    getGameYPos
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_guidedhacking_GH_1Tools_GHTools_getGameYPos
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
